stages:
  split:
    cmd: python src/data/data_split.py
    deps:
    - data/raw_data/clean_data.csv
    - src/data/data_split.py
    - params.yaml
    params:
    - split.drop_columns
    - split.random_state
    - split.target_col
    - split.test_size
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  normalize:
    cmd: python src/data/normalize.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/normalize.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  gridsearch:
    cmd: python src/models/grid_search.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/grid_search.py
    - params.yaml
    params:
    - grid_search
    outs:
    - models/best_params.pkl
  training:
    cmd: python src/models/training.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    - src/models/training.py
    outs:
    - models/rf_model.pkl
  evaluate:
    cmd: python src/models/evaluate.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/rf_model.pkl
    - src/models/evaluate.py
    outs:
    - data/prediction.csv
    metrics:
    - metrics/scores.json:
        cache: false
